# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20160214_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('text', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('main', models.BooleanField(default=False, verbose_name='\u041d\u0430 \u0433\u043b\u0430\u0432\u043d\u0443\u044e')),
                ('main_img', models.ImageField(upload_to='./static/img', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u0443\u044e')),
                ('images', models.ImageField(upload_to='./static/img', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438')),
                ('city', models.CharField(choices=[(0, '\u0426\u0430\u043d\u0434\u0440\u0438\u043f\u0448'), (1, '\u0413\u0430\u0433\u0440\u0430'), (2, '\u0413\u0443\u0434\u0430\u0443\u0442\u0430'), (3, '\u041f\u0438\u0446\u0443\u043d\u0434\u0430'), (4, '\u041d\u043e\u0432\u044b\u0439 \u0410\u0444\u043e\u043d'), (5, '\u0421\u0443\u0445\u0443\u043c')], max_length=1, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('phone', models.IntegerField(verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('house_type', models.CharField(choices=[(0, '\u041c\u0438\u043d\u0438-\u043e\u0442\u0435\u043b\u044c'), (1, '\u0427\u0430\u0441\u0442\u043d\u044b\u0439 \u0434\u043e\u043c'), (2, '\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430'), (3, '\u041a\u043e\u0442\u0442\u0435\u0434\u0436'), (4, '\u041e\u0442\u0435\u043b\u044c')], max_length=1, verbose_name='\u0422\u0438\u043f \u043f\u043e\u043c\u0435\u0449\u0435\u043d\u0438\u044f')),
                ('price', models.IntegerField(verbose_name='\u0426\u0435\u043d\u0430')),
                ('sea', models.IntegerField(verbose_name='\u0414\u043e \u043c\u043e\u0440\u044f')),
                ('hot_w', models.BooleanField(default=False, verbose_name='\u0413\u043e\u0440\u044f\u0447\u0430\u044f \u0432\u043e\u0434\u0430')),
                ('lavatory', models.BooleanField(default=False, verbose_name='\u0423\u0431\u043e\u0440\u043d\u0430\u044f')),
                ('w_machine', models.BooleanField(default=False, verbose_name='\u0421\u0442\u0438\u0440\u0430\u043b\u044c\u043d\u0430\u044f \u043c\u0430\u0448\u0438\u043d\u0430')),
                ('shower', models.BooleanField(default=False, verbose_name='\u0414\u0443\u0448')),
                ('fridge', models.BooleanField(default=False, verbose_name='\u0425\u043e\u043b\u043e\u0434\u0438\u043b\u044c\u043d\u0438\u043a')),
                ('tv', models.BooleanField(default=False, verbose_name='\u0422\u0435\u043b\u0435\u0432\u0438\u0437\u043e\u0440')),
                ('internet', models.BooleanField(default=False, verbose_name='\u0418\u043d\u0442\u0435\u0440\u043d\u0435\u0442')),
                ('conditioner', models.BooleanField(default=False, verbose_name='\u041a\u043e\u043d\u0434\u0438\u0446\u0438\u043e\u043d\u0435\u0440')),
                ('safe', models.BooleanField(default=False, verbose_name='\u0421\u0435\u0439\u0444')),
                ('food', models.BooleanField(default=False, verbose_name='\u041f\u0438\u0442\u0430\u043d\u0438\u0435')),
                ('balcony', models.BooleanField(default=False, verbose_name='\u0411\u0430\u043b\u043a\u043e\u043d')),
            ],
        ),
        migrations.AlterField(
            model_name='excursions',
            name='main_img',
            field=models.ImageField(upload_to='./static/img', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u0443\u044e'),
        ),
    ]
