# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20160216_0343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursions',
            old_name='main_img',
            new_name='image',
        ),
    ]
