# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20160216_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='./static/img', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438')),
            ],
        ),
        migrations.RemoveField(
            model_name='houses',
            name='images',
        ),
        migrations.AlterField(
            model_name='houses',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('main_img', '240x180', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Houses'),
        ),
    ]
