# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20160217_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursions',
            name='slide_cropping',
            field=image_cropping.fields.ImageRatioField('slide_image', '1000x400', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='slide cropping'),
        ),
        migrations.AddField(
            model_name='excursions',
            name='slide_image',
            field=models.ImageField(blank=True, upload_to='./img', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0432 \u0441\u043b\u0430\u0439\u0434\u0435\u0440'),
        ),
        migrations.AlterField(
            model_name='excursions',
            name='main',
            field=models.BooleanField(default=False, verbose_name='\u041d\u0430 \u0433\u043b\u0430\u0432\u043d\u0443\u044e'),
        ),
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.ImageField(upload_to='./img', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438'),
        ),
    ]
