# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_excursions_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='map',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AddField(
            model_name='houses',
            name='map_visible',
            field=models.IntegerField(default=False, verbose_name='\u041f\u043e\u043a\u0430\u0437\u0430\u0442\u044c \u043a\u0430\u0440\u0442\u0443 \u043d\u0430 \u0441\u0442\u0430\u0440\u0430\u043d\u0438\u0446\u0435'),
        ),
        migrations.AlterField(
            model_name='excursions',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '450x300', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='excursions',
            name='slide_cropping',
            field=image_cropping.fields.ImageRatioField('slide_image', '1000x350', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='slide cropping'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('main_img', '320x240', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
