# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20160303_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='\u0417\u0430\u0435\u0437\u0434'),
        ),
        migrations.AddField(
            model_name='houses',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='\u0412\u044b\u0435\u0437\u0434'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='map_visible',
            field=models.BooleanField(default=False, verbose_name='\u041f\u043e\u043a\u0430\u0437\u0430\u0442\u044c \u043a\u0430\u0440\u0442\u0443 \u043d\u0430 \u0441\u0442\u0430\u0440\u0430\u043d\u0438\u0446\u0435'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='phone',
            field=models.IntegerField(blank=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
    ]
