# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20160303_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='park',
            field=models.BooleanField(default=False, verbose_name='\u041f\u0430\u0440\u043a\u043e\u0432\u043a\u0430'),
        ),
    ]
